# Reprojection error (重投影误差): 0.7709px
image_width: 460
image_height: 576
# Left camera intrinsics (fx, fy, cx, cy) / 左相机内参
camera_matrix_left: [415.13854964767228, 0, 170.81258210205797, 0, 415.97454072666397, 278.63156830840558, 0, 0, 1]  # Left camera distortion coefficients (k1, k2, p1, p2, k3) / 左相机畸变系数
distort_coeffs_left: [0.21370251687597794, 0.23812199083254035, -0.0064927890069388563, -0.014740791245691949, -0.88322915926999168]
# Right camera intrinsics (fx, fy, cx, cy) / 右相机内参
camera_matrix_right: [410.61046956075251, 0, 215.1856478723214, 0, 411.71541924915908, 292.65163846616758, 0, 0, 1]  # Right camera distortion coefficients (k1, k2, p1, p2, k3) / 右相机畸变系数
distort_coeffs_right: [0.18877710346783097, 0.38549047046153961, -0.0031466862146082328, -0.013073908113297287, -1.5530218471151622]
# Rotation matrix between left and right cameras / 左右相机旋转矩阵
R: [0.99996738047790046, -0.00046454810412112455, 0.0080636328800803812, 0.00055141095206916386, 0.99994181434371776, -0.010773294433724838, -0.0080581589788049079, 0.010777389389492515, 0.999909452876519]  # Translation vector between left and right cameras / 左右相机平移向量
T: [-25.546247531068779, -0.97412292991385852, -5.2707929283513923]  # Essential matrix / 本质矩阵
E: [0.01075601038092676, 5.2599877416768139, -1.0308185300009622, -5.4764767215222383, 0.27777039394477065, 25.501432652677959, 0.96000467381651733, -25.54521363285091, 0.28307221601591381]  # Fundamental matrix / 基础矩阵
F: [-3.0307452197709815e-07, -0.00014791399293042156, 0.053323227266892051, 0.00015389777768779945, -7.7901060536431724e-06, -0.3216183237304393, -0.056080342532999282, 0.32906940904372245, 1]