# 标定板类型: "chessboard" (棋盘格) 或 "circles_grid" (对称圆形网格)
pattern_type: "chessboard"

# 标定板的尺寸 (内部角点或圆心的数量)
pattern_cols: 10  # 列数
pattern_rows: 7  # 行数

num_images: 40 # <--- 在这里添加

# 标定板每个单元的物理尺寸 (单位: 毫米)
# 如果是棋盘格，则为方格的边长
# 如果是圆形网格，则为相邻圆心的距离
unit_size_mm: 18.0

# 相机参数
camera:
    left_index: 4
    right_index: 2

verify_stereo:
    stereo_params_path: "configs/stereo_params.yaml"
    left_image_path: "imgs/left/000.jpg"
    right_image_path: "imgs/right/000.jpg"